[package]
name = "impostorbot"
version = "0.1.0"
edition = "2024"

[workspace]
# Todos los miembros (crates) de nuestro proyecto
members = [
    "game_core",
    "web_api",
    "telegram_bot",
]

# Opcional: Resolver las dependencias a nivel de workspace
resolver = "2"
